# BASE
BASE=#0e0e0e
SURFACE=#1a1a1a
OVERLAY=#2a2a2a

# TEXT
TEXT=#e0e0e0
TEXT_MUTED=#666666

# ACCENTS
ACCENT_PRIMARY=#00ff9f
ACCENT_SECONDARY=bf5fff

# SEMANTIC
BORDER_ACTIVE=$ACCENT_PRIMARY
BORDER_INACTIVE=$OVERLAY
