layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.79, match:namespace swaync-control-center
layerrule = ignore_alpha 0.79, match:namespace swaync-notification-window
